server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_product
    username: postgres
    password: postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
